# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.012 
    
# e.g. "anas_krystallinus"    
species.name <- "sansomus_devonii"
    
# e.g. "red"    
color <- "gold1"
    
# For list of colours available in R, see http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf
